### ISSUE TITLE
Series 4 Processor Support

### ISSUE THREAD

**Issue by JaronrH** [sahajquinci/simplewmqttclient#9]
[SimplMqttClient.zip](https://github.com/sahajquinci/simplewmqttclient/files/11101859/SimplMqttClient.zip)

Thanks for building this!  I just finished porting it over the the Crestron Series 4 processors (see attached for no tls build as well as modified client and project files).

In the process, I found that the SecureTCPClient was throwing errors even when the SSL Cert/Key was // in Simpl (Socket error shows up in Mosquitto).  I changed the code to use a preprocessor flag to switch between SecureTCPClient and TCPClient for TLS vs NON-TLS builds.  I still cannot get QoS1 to work but QoS0 is all I needed so I didn't dive any farther into that.

Thanks again for all the work you did on this!

**Comment by sahajquinci** [comment]
@JaronrH  thank you very much for this porting, would you like to make a PR to include your porting in the master branch ? :)

**Comment by sahajquinci** [comment]
@JaronrH This is great work, one thing that puzzles me though is why ? 
This client was built the way it is because the 3-series is stuck on .NET 3.5 Compact framework.
I haven't been working with Crestron technology for quite some time now, but isn't the 4 series supporting .NET Framework 4.7  ?

In this case I would expect this client https://www.nuget.org/packages/MQTTnet/  to run on a 4-series and be way more efficient than mine. Also it should be possible to encapsulate it in a module, unless also this .NET 4.7 version doesn't support all the standard libraries but only a few selected ones and certain features rely on Crestron .NET libraries like it is for the 3.5 compact framework🙂

**Comment by JaronrH** [comment]
You are correct, v4 does run Nuget packages.  I haven't tried MQTTnet myself but there is a very good chance it could work.  With that said, I've seen som libraries (ex: influxdb) that just don't work with Crestron's reverse-compiling to Simp#/+ (when they try to extract the interface, etc). 

So, to answer your question _why_, well, **it was a mater of convivence**:  It was much easier and **faster** to use your modules - which already work with a dumber CF3.5 _and_ have Simp+ wrappers - then it would be for me to build all of that from scratch [when your already library does everything we need]!

**Comment by sahajquinci** [comment]
Understood. 
I see your answer is plural. I am sure you tested your use case thoroughly with this client, but please be aware that this is an amateur project done by a younger version of me who was getting for the first time his hands on .NET, hence it's not very robust, and it's absolutely filled with bugs :D

**Comment by JaronrH** [comment]
Completely understand! I feel the same about some of my old code too!!

 It's for a proof of concept just now so I'm not too concerned. I can build my own off of the official MQTTnet client down the road if needed!

**Comment by JaronrH** [comment]
Quick Update: POC went over really well so we're now taking the time to build off of the official MQTTNet project.  Thanks again!
